function(auto_target_add)
    foreach(filename IN LISTS ${ARGV0})
        get_filename_component(targetname ${filename} NAME_WE)
        message(STATUS "add target: ${targetname}")
        add_executable(${targetname} ${filename})
        foreach(libname IN LISTS ${ARGV1})
            target_link_libraries(${targetname} ${libname})
        endforeach()
        target_compile_options(${targetname} PRIVATE ${GNU_FLAGS})
    endforeach()
endfunction()