name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        
        - name: Checkout submodules
          run: git submodule update --init --recursive

        - uses: conda-incubator/setup-miniconda@v2
          with:
            auto-update-conda: true
            environment-name: ci-env
            python-version: 3.9
            auto-activate-base: false
            activate-environment: ci-env
        
        - name: Install Python dependencies
          shell: bash -l {0}
          run: |
            pip install numpy

        - name: Setup Ninja
          uses: ashutoshvarma/setup-ninja@master
          with:
            version: 1.10.0
        
        - name: Debug config
          working-directory: ${{github.workspace}}
          run: bash ./config_debug.sh

        - name: Debug build
          working-directory: ${{github.workspace}}
          run: bash ./build_debug.sh

        - name: Release config
          working-directory: ${{github.workspace}}
          run: bash ./config_release.sh

        - name: Release build
          working-directory: ${{github.workspace}}
          run: bash ./build_release.sh

        - name: Run st
          working-directory: ${{github.workspace}}
          run: bash ./run_ut.sh
